# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  release:
    types:
      - published
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Publish Extension
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
